version: "3.7"

services:
    app:
        depends_on: 
            - db
        restart: always
        build:
            context: .
        ports: 
            - 3000:3000

    db:
        image: mysql:latest
        container_name: mysql
        volumes: 
            - db_data:/var/lib/mysql
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
        ports: 
            - 3306:3306
    phpmyadmin:
        depends_on: 
            - db
        image: phpmyadmin/phpmyadmin:latest
        container_name: phpmyadmin
        environment: 
            - PMA_ARBITRARY=1
        restart: always
        ports: 
            - 5000:80
 


volumes: 
    db_data: